### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by martielafreitas** [piercelab/tcr_docking_angle#1]
```
$ make
g++  -o tcr_docking_angle tcr_docking_angle.cc tcr_complex.cc  -lgsl -lgslcblas -Lfast -lfast
/usr/bin/ld: cannot find -lfast
collect2: error: ld returned 1 exit status
make: *** [makefile:10: tcr_docking_angle] Error 1
```

So far I know that I may be missing the fast library.
Do you know which version I can find fast library? Or how to install it?

I'm currently using Ubuntu 20.04.6 LTS, and g++ 9.4.0.
Thanks,

**Comment by bpierce12** [comment]
The fast library code files are in the "fast" subfolder. If you go into that folder and "make", it will hopefully build the fast library for you, which you can then copy into the compilation directory for tcr_docking_angle.

Let me know if that works, and/or if you have any more questions.

**Comment by martielafreitas** [comment]
Thank you for answering so fast!

So, I have ran make on the fast folder. The only libfast in the fast folder is a .dylib file.
Sorry about my lack of knowledge here but was this supposed to work on Ubuntu?

Well, I tested with this one and got the same error from the first message.
After that I have compiled the .so file with the following commands:

```
$ gcc -fPIC -I. -c fast.c -o fast.o
fast.c: In function ‘main’:
fast.c:108:3: warning: format not a string literal and no format arguments [-Wformat-security]
  108 |   printf(usage);
      |   ^~~~~~
$ gcc -shared -o libfast.so fast.o
```
Even with the libfast.so, it doesn't work.
My error now is:

```
$ make
g++  -o tcr_docking_angle tcr_docking_angle.cc tcr_complex.cc  -lgsl -lgslcblas -Lfast -lfast
/usr/bin/ld: /tmp/ccdpDCFW.o: in function `TCRComplex::CalcTCRRotVector(double&, double&, double&)':
tcr_complex.cc:(.text+0x39d5): undefined reference to `alignment_create'
/usr/bin/ld: tcr_complex.cc:(.text+0x39e4): undefined reference to `jz_protein_null'
/usr/bin/ld: tcr_complex.cc:(.text+0x39f3): undefined reference to `jz_protein_null'
/usr/bin/ld: tcr_complex.cc:(.text+0x3a62): undefined reference to `bp_protein_load'
/usr/bin/ld: tcr_complex.cc:(.text+0x3aa3): undefined reference to `bp_protein_load'
/usr/bin/ld: tcr_complex.cc:(.text+0x3adc): undefined reference to `vote_pairwise'
/usr/bin/ld: tcr_complex.cc:(.text+0x3bf4): undefined reference to `vote_rms_fit'
/usr/bin/ld: tcr_complex.cc:(.text+0x3cd2): undefined reference to `jz_protein_clear'
/usr/bin/ld: tcr_complex.cc:(.text+0x3ce1): undefined reference to `jz_protein_clear'
collect2: error: ld returned 1 exit status
make: *** [makefile:10: tcr_docking_angle] Error 1
```

I'm certainly doing something wrong here.
I would be very glad with any help you can provide.

**Comment by bpierce12** [comment]
Happy to help! What I think you'll want to do is this within that "fast"
directory.
rm libfast.dylib
make clean
make
mv libfast.dylib libfast.so
cd ..
make

The first four lines will clear out the executables and library files from
that fast directory, remake the fast library, and rename the file to a
convention used by Ubuntu ("libfast.dylib" is more for Mac, so "libfast.so"
is better). Then you can go back to the main directory and compile (last
two lines above).

Let me know if that helps, and if anything else is needed.

**Comment by martielafreitas** [comment]
It is working now.
Thank you a lot!
